export const accountTypes = [
  "Digital Bank",
  "E-Wallet",
  "Investments",
  "Loan",
  "Physical Bank",
  "Credit Card",
  "Cash",
];

export const accountProviders: Record<(typeof accountTypes)[number], string[]> =
  {
    "Digital Bank": [
      "GoTyme Bank",
      "MariBank",
      "Maya Bank",
      "CIMB Bank Philippines",
      "Tonik Digital Bank",
      "UnionDigital Bank",
      "UNO Digital Bank",
      "OwnBank",
      "Komo",
      "Salmon Bank",
    ],
    "E-Wallet": [
      "GCash",
      "Maya",
      "GrabPay",
      "ShopeePay",
      "Coins.ph",
      "PalawanPay",
    ],
    Investments: [
      "COL Financial",
      "First Metro Sec",
      "BPI Trade",
      "GInvest",
      "Maya Funds / Maya Crypto",
      "PDAX",
      "Gotrade",
      "eToro",
    ],
    Loan: [
      "BillEase",
      "Home Credit Philippines",
      "Tala",
      "GLoan / GCredit",
      "Maya Credit / Maya Personal Loan",
      "SLoan",
      "JuanHand",
      "Cashalo",
      "SPayLater",
      "Lazada PayLater",
      "TikTok PayLater",
    ],
    "Physical Bank": [
      "BDO Unibank",
      "BPI",
      "Metrobank",
      "LandBank",
      "Security Bank",
      "UnionBank of the Philippines",
      "PNB",
      "RCBC",
      "EastWest Bank",
      "China Bank",
    ],
    "Credit Card": [
      "BDO CC",
      "BPI CC",
      "UnionBank CC",
      "Metrobank CC",
      "RCBC CC",
      "EastWest CC",
      "Security Bank CC",
      "HSBC Philippines",
    ],
    Cash: [
      "Wallet",
      "Cash on Hand",
      "Petty Cash",
      "Piggy Bank / Alkansya",
      "Safe / Vault",
    ],
  };
