export const categories = [
  "Business",
  "Clothes",
  "Debt",
  "Eat Out",
  "Electricity",
  "Emergency Fund",
  "Essentials",
  "Food",
  "Gala",
  "Gift",
  "Grocery",
  "Healthcare",
  "Internet",
  "Investments",
  "Leisure",
  "Load",
  "Loan",
  "Miscellaneous",
  "Mobile Data",
  "MP2",
  "Non-Essentials",
  "Online Bank",
  "Pagibig",
  "Philhealth",
  "Reimbursement",
  "Salary",
  "Sanity Check",
  "Saving Goal",
  "Savings",
  "Side Hustle",
  "Sinking Fund",
  "SSS",
  "Subscriptions",
  "Transportation",
  "Utilities",
  "Utilities Payment",
];
