export const transactions = [
  {
    id: "1",
    dateTime: "2024-05-20T10:30:00Z",
    transaction_category_id: 5,
    transaction_category_name: "Food & Drink",
    amount: 6.5,
    transaction_name: "Starbucks Coffee",
    transaction_note: "Morning caffeine fix",
    transaction_type_id: 1,
    transaction_type_name: "Expense",
    account_to_deduct_id: 101,
    account_to_deduct_name: "Main Checking",
    budget_id: 2,
    budget_name: "Personal Luxuries",
    user_id: 42,
  },
  {
    id: "2",
    dateTime: "2024-05-25T09:00:00Z",
    transaction_category_id: 10,
    transaction_category_name: "Salary",
    amount: 4500.0,
    transaction_name: "Monthly Salary",
    transaction_note: "May Paycheck",
    transaction_type_id: 2,
    transaction_type_name: "Income",
    account_to_add_id: 102,
    account_to_add_name: "Savings Account",
    user_id: 42,
  },
  {
    id: "3",
    dateTime: "2024-05-26T14:15:00Z",
    transaction_category_id: 8,
    transaction_category_name: "Electronics",
    amount: 200.0,
    transaction_name: "MacBook Pro",
    transaction_note: "Interest-free installment plan",
    transaction_type_id: 1,
    transaction_type_name: "Expense",
    account_to_deduct_id: 105,
    account_to_deduct_name: "Credit Card",
    number_of_installment: 12,
    total_installment_amount: 2400.0,
    fee: 0.0,
    user_id: 42,
  },
];
