import { AccountTypeName } from "@/types/entities/accountTypes.type";
import {
  CategoryDetail,
  CategoryName,
  TransactionType,
} from "@/types/entities/categories.type";
import { Ionicons } from "@expo/vector-icons";

export const THEME_COLORS = [
  "#2563EB",
  "#16A34A",
  "#D97706",
  "#DC2626",
  "#9333EA",
];

const allTypes: TransactionType[] = [
  "Expense",
  "Income",
  "Transfer",
  "Investment",
];

export const categoryIconsAndTypes: Record<CategoryName, CategoryDetail> = {
  Business: { type: allTypes, icon: "business" },
  Clothes: { type: allTypes, icon: "shirt" },
  Debt: { type: allTypes, icon: "card" },
  "Eat Out": { type: allTypes, icon: "restaurant" },
  Electricity: { type: allTypes, icon: "flash" },
  "Emergency Fund": { type: allTypes, icon: "shield-checkmark" },
  Essentials: { type: allTypes, icon: "checkmark-circle" },
  Food: { type: allTypes, icon: "fast-food" },
  Gala: { type: allTypes, icon: "airplane" },
  Gift: { type: allTypes, icon: "gift" },
  Grocery: { type: allTypes, icon: "cart" },
  Healthcare: { type: allTypes, icon: "medical" },
  Internet: { type: allTypes, icon: "globe" },
  Investments: { type: allTypes, icon: "trending-up" },
  Leisure: { type: allTypes, icon: "game-controller" },
  Load: { type: allTypes, icon: "phone-portrait" },
  Loan: { type: allTypes, icon: "cash" },
  Miscellaneous: { type: allTypes, icon: "ellipsis-horizontal-circle" },
  "Mobile Data": { type: allTypes, icon: "cellular" },
  MP2: { type: allTypes, icon: "stats-chart" },
  "Non-Essentials": { type: allTypes, icon: "close-circle" },
  "Online Bank": { type: allTypes, icon: "desktop" },
  Pagibig: { type: allTypes, icon: "home" },
  Philhealth: { type: allTypes, icon: "heart-half" },
  Reimbursement: { type: allTypes, icon: "return-down-back" },
  Salary: { type: allTypes, icon: "wallet" },
  "Sanity Check": { type: allTypes, icon: "heart" },
  "Saving Goal": { type: allTypes, icon: "flag" },
  Savings: { type: allTypes, icon: "archive" },
  "Side Hustle": { type: allTypes, icon: "hammer" },
  "Sinking Fund": { type: allTypes, icon: "water" },
  SSS: { type: allTypes, icon: "briefcase" },
  Subscriptions: { type: allTypes, icon: "calendar" },
  Transportation: { type: allTypes, icon: "car" },
  Utilities: { type: allTypes, icon: "construct" },
  "Utilities Payment": { type: ["Expense"], icon: "card" },
};

export const accountTypeIcons: Record<
  AccountTypeName,
  keyof typeof Ionicons.glyphMap
> = {
  "Digital Bank": "globe",
  "E-Wallet": "wallet",
  Investments: "trending-up",
  Loan: "cash",
  "Physical Bank": "business",
  "Credit Card": "card",
  Cash: "cash",
};

export const accountProviderUI = {
  "Digital Bank": [
    {
      name: "GoTyme Bank",
      color1: "#00C3FF",
      color2: "#0052FF",
      "logo-link": "/assets/logos/gotyme_bank.png",
    },
    {
      name: "MariBank",
      color1: "#FF7A00",
      color2: "#9d2500",
      "logo-link": "/assets/logos/maribank.png",
    },
    {
      name: "Maya Bank",
      color1: "#00E500",
      color2: "#014223",
      "logo-link": "/assets/logos/maya_bank.png",
    },
    {
      name: "CIMB Bank Philippines",
      color1: "#E00025",
      color2: "#8A0017",
      "logo-link": "/assets/logos/cimb_bank.png",
    },
    {
      name: "Tonik Digital Bank",
      color1: "#6F2C91",
      color2: "#F26522",
      "logo-link": "/assets/logos/tonik_bank.png",
    },
    {
      name: "UnionDigital Bank",
      color1: "#FF6B00",
      color2: "#003E7E",
      "logo-link": "/assets/logos/uniondigital_bank.png",
    },
    {
      name: "UNO Digital Bank",
      color1: "#FFD100",
      color2: "#000000",
      "logo-link": "/assets/logos/uno_digital_bank.png",
    },
    {
      name: "OwnBank",
      color1: "#4D2CA1",
      color2: "#30EC5D",
      "logo-link": "/assets/logos/ownbank.png",
    },
    {
      name: "Komo",
      color1: "#00A859",
      color2: "#FDE100",
      "logo-link": "/assets/logos/komo.png",
    },
  ],
  "E-Wallet": [
    {
      name: "GCash",
      color1: "#007BFF",
      color2: "#001d45",
      "logo-link": "/assets/logos/gcash.png",
    },
    {
      name: "Maya",
      color1: "#014223",
      color2: "#00E500",
      "logo-link": "/assets/logos/maya.png",
    },
    {
      name: "GrabPay",
      color1: "#00B14F",
      color2: "#005e29",
      "logo-link": "/assets/logos/grabpay.png",
    },
    {
      name: "ShopeePay",
      color1: "#EE4D2D",
      color2: "#FF7337",
      "logo-link": "/assets/logos/shopeepay.png",
    },
    {
      name: "Coins.ph",
      color1: "#FF9D42",
      color2: "#FAFAFA",
      "logo-link": "/assets/logos/coins_ph.png",
    },
    {
      name: "PalawanPay",
      color1: "#FEB416",
      color2: "#001D11",
      "logo-link": "/assets/logos/palawanpay.png",
    },
  ],
  Investments: [
    {
      name: "COL Financial",
      color1: "#003366",
      color2: "#0055A4",
      "logo-link": "/assets/logos/col_financial.png",
    },
    {
      name: "First Metro Sec",
      color1: "#004B87",
      color2: "#0066B3",
      "logo-link": "/assets/logos/first_metro_sec.png",
    },
    {
      name: "BPI Trade",
      color1: "#B30000",
      color2: "#E60000",
      "logo-link": "/assets/logos/bpi_trade.png",
    },
    {
      name: "GInvest",
      color1: "#007BFF",
      color2: "#0056D2",
      "logo-link": "/assets/logos/ginvest.png",
    },
    {
      name: "Maya Funds / Maya Crypto",
      color1: "#014223",
      color2: "#00E500",
      "logo-link": "/assets/logos/maya_invest.png",
    },
    {
      name: "PDAX",
      color1: "#000000",
      color2: "#333333",
      "logo-link": "/assets/logos/pdax.png",
    },
    {
      name: "Gotrade",
      color1: "#00C853",
      color2: "#00E676",
      "logo-link": "/assets/logos/gotrade.png",
    },
    {
      name: "eToro",
      color1: "#6EAE41",
      color2: "#548A31",
      "logo-link": "/assets/logos/etoro.png",
    },
  ],
  Loan: [
    {
      name: "BillEase",
      color1: "#003D73",
      color2: "#005A9E",
      "logo-link": "/assets/logos/billease.png",
    },
    {
      name: "Home Credit Philippines",
      color1: "#E3000F",
      color2: "#B3000C",
      "logo-link": "/assets/logos/home_credit.png",
    },
    {
      name: "Tala",
      color1: "#00A59B",
      color2: "#00827B",
      "logo-link": "/assets/logos/tala.png",
    },
    {
      name: "GLoan / GCredit",
      color1: "#007BFF",
      color2: "#0056D2",
      "logo-link": "/assets/logos/gloan.png",
    },
    {
      name: "Maya Credit / Maya Personal Loan",
      color1: "#014223",
      color2: "#00E500",
      "logo-link": "/assets/logos/maya_credit.png",
    },
    {
      name: "SLoan",
      color1: "#EE4D2D",
      color2: "#FF7337",
      "logo-link": "/assets/logos/sloan.png",
    },
    {
      name: "JuanHand",
      color1: "#9236B5",
      color2: "#9F95E0",
      "logo-link": "/assets/logos/juanhand.png",
    },
    {
      name: "Cashalo",
      color1: "#ED1C24",
      color2: "#C1171D",
      "logo-link": "/assets/logos/cashalo.png",
    },
  ],
  "Physical Bank": [
    {
      name: "BDO Unibank",
      color1: "#0033A0",
      color2: "#FDB913",
      "logo-link": "/assets/logos/bdo.png",
    },
    {
      name: "BPI",
      color1: "#390000",
      color2: "#980000",
      "logo-link": "/assets/logos/bpi.png",
    },
    {
      name: "Metrobank",
      color1: "#0033A0",
      color2: "#0055A4",
      "logo-link": "/assets/logos/metrobank.png",
    },
    {
      name: "LandBank",
      color1: "#005A32",
      color2: "#008040",
      "logo-link": "/assets/logos/landbank.png",
    },
    {
      name: "Security Bank",
      color1: "#003A6C",
      color2: "#00529B",
      "logo-link": "/assets/logos/security_bank.png",
    },
    {
      name: "UnionBank of the Philippines",
      color1: "#FF6B00",
      color2: "#003E7E",
      "logo-link": "/assets/logos/unionbank.png",
    },
    {
      name: "PNB",
      color1: "#0033A0",
      color2: "#ED1C24",
      "logo-link": "/assets/logos/pnb.png",
    },
    {
      name: "RCBC",
      color1: "#003A6C",
      color2: "#00529B",
      "logo-link": "/assets/logos/rcbc.png",
    },
    {
      name: "EastWest Bank",
      color1: "#00A859",
      color2: "#421B52",
      "logo-link": "/assets/logos/eastwest_bank.png",
    },
    {
      name: "China Bank",
      color1: "#E31837",
      color2: "#FFB81C",
      "logo-link": "/assets/logos/china_bank.png",
    },
  ],
  "Credit Card": [
    {
      name: "BDO CC",
      color1: "#0033A0",
      color2: "#FDB913",
      "logo-link": "/assets/logos/bdo_credit.png",
    },
    {
      name: "BPI CC",
      color1: "#B30000",
      color2: "#E60000",
      "logo-link": "/assets/logos/bpi_credit.png",
    },
    {
      name: "UnionBank CC",
      color1: "#FF6B00",
      color2: "#003E7E",
      "logo-link": "/assets/logos/unionbank_credit.png",
    },
    {
      name: "Metrobank CC",
      color1: "#0033A0",
      color2: "#0055A4",
      "logo-link": "/assets/logos/metrobank_credit.png",
    },
    {
      name: "RCBC CC",
      color1: "#003A6C",
      color2: "#00529B",
      "logo-link": "/assets/logos/rcbc_credit.png",
    },
    {
      name: "EastWest CC",
      color1: "#00A859",
      color2: "#421B52",
      "logo-link": "/assets/logos/eastwest_credit.png",
    },
    {
      name: "Security Bank CC",
      color1: "#003A6C",
      color2: "#00736f",
      "logo-link": "/assets/logos/security_bank_credit.png",
    },
    {
      name: "HSBC Philippines",
      color1: "#DB0011",
      color2: "#FF0000",
      "logo-link": "/assets/logos/hsbc.png",
    },
  ],
  Cash: [
    {
      name: "Wallet",
      color1: "#8B4513",
      color2: "#A0522D",
      "logo-link": "/assets/logos/wallet.png",
    },
    {
      name: "Cash on Hand",
      color1: "#2E8B57",
      color2: "#3CB371",
      "logo-link": "/assets/logos/cash.png",
    },
    {
      name: "Petty Cash",
      color1: "#4682B4",
      color2: "#5F9EA0",
      "logo-link": "/assets/logos/petty_cash.png",
    },
    {
      name: "Piggy Bank / Alkansya",
      color1: "#FF69B4",
      color2: "#FFB6C1",
      "logo-link": "/assets/logos/piggy_bank.png",
    },
    {
      name: "Safe / Vault",
      color1: "#708090",
      color2: "#778899",
      "logo-link": "/assets/logos/safe_vault.png",
    },
  ],
};
